export const NAMESPACE = "employeeChecks";

export const FILTER_EMPLOYEE_CHECKS_LOADING = 'FILTER_EMPLOYEE_CHECKS_LOADING';
export const FILTER_EMPLOYEE_CHECKS_SUCCESS = 'FILTER_EMPLOYEE_CHECKS_SUCCESS';
export const FILTER_EMPLOYEE_CHECKS_FAILURE = 'FILTER_EMPLOYEE_CHECKS_FAILURE';
export const DELETE_CHECK_DATE_SUCCESS = 'DELETE_CHECK_DATE_SUCCESS';
export const DELETE_CHECK_PERIOD_SUCCESS = 'DELETE_GROUP_EMPLOYEES_SUCCESS';