export const NAMESPACE = "projects";

export const SET_PROJECTS_LOADING = 'SET_PROJECTS_LOADING';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAILURE = 'GET_PROJECTS_FAILURE';
export const DELETE_PROJECTS_SUCCESS = 'DELETE_PROJECTS_SUCCESS';
export const DELETE_GROUP_PROJECTS_SUCCESS = 'DELETE_GROUP_PROJECTS_SUCCESS'