export const NAMESPACE = "calendars";

export const SET_CALENDARS_LOADING = 'SET_CALENDARS_LOADING';
export const GET_CALENDARS_SUCCESS = 'GET_CALENDARS_SUCCESS';
export const GET_CALENDARS_FAILURE = 'GET_CALENDARS_FAILURE';
export const DELETE_CALENDARS_SUCCESS = 'DELETE_CALENDARS_SUCCESS';
export const DELETE_GROUP_CALENDARS_SUCCESS = 'DELETE_GROUP_CALENDARS_SUCCESS';